version: "2.1"
services:
    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - "./backend/:/usr/src/app"
        user: ${LOCAL_USER}

    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - "./backend/public/:/usr/src/app"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
        ports:
            - "80:80"
        depends_on:
            - php